GT-2228 Improve styling of accordions
CruGlobal/know-god-web pull request #151
Opened 2023-12-15 19:40 UTC by caleballdrin

## Description
https://jira.cru.org/browse/GT-2228
- Improve styling of accordions [1 Day]
* Change heading font to Source Sans Pro
* Make box more rounded
* Add more spacing between accordions

2023-12-15 20:30 UTC, wrandall22 commented on tool-versions
This file shouldn't exist.

2023-12-15 21:19 UTC, dr-bizz commented on tool-versions
You can remove that file @caleballdrin. I've added it to my PR. Also, it should have been `.tool-versions`

2023-12-15 22:24 UTC, frett commented on tool-versions
I think he was referring to the extra `tool-versions` file, and not the `.tool-versions` file. Caleb committed 2 different files.

2023-12-22 22:26 UTC, dr-bizz requested changes

2023-12-22 22:26 UTC, dr-bizz commented on .tool-versions
> +nodejs 18.13.0
You can remove this as I've added this. You'll need to merge main into your branch as I made some large changes.

2023-12-22 22:26 UTC, dr-bizz commented on src/app/new-page/component/content-accordion/content-accordion.component.css
> +  -ms-transform: rotate(180deg);
You no longer need to prefix `transform` as 98% of browsers support it.

https://caniuse.com/?search=transform

2023-12-22 22:26 UTC, dr-bizz commented on src/app/new-page/component/content-accordion/content-accordion.component.css
> +  -moz-transition: all 0.2s linear;
You don't need to prefixe `transform` - https://caniuse.com/?search=transform`

2023-12-22 22:26 UTC, dr-bizz commented on src/app/new-page/component/content-accordion/content-accordion.component.html
> +    <div class="accordion mw568">
Thank you for fixing this

2023-12-22 22:26 UTC, dr-bizz commented on src/app/new-page/component/content-accordion/content-accordion.component.css
> +  background-color: var(--kg-gray-medium-dark);
On mobile, we might need to make the padding less when get below 400px. This isn;t urgent as they could use the App when on smaller devices.

2023-12-22 22:26 UTC, dr-bizz reviewed
Great work!! 🔥

2024-01-16 21:39 UTC, dr-bizz commented
Something is wrong with this PR, I doubt you edited 215 files.

2024-01-16 21:44 UTC, dr-bizz requested changes
Need to merge the latest version of `master` into your  branch to fix all the conflicts and files that should be already deleted.

2024-01-16 21:49 UTC, frett commented on src/app/page/component/content-accordion/content-accordion.component.css
> +}
you repeated this css rule

2024-01-25 19:29 UTC, dr-bizz approved these changes
The changes look great. Awesome work!

2024-01-25 21:30 UTC, merged